### ISSUE TITLE
Docs build failing on main branch

### ISSUE THREAD

**Issue by caleb-johnson** [Qiskit-Extensions/circuit-knitting-toolbox#557]
tox -e docs
pkg: install_requires> python -I -m pip install hatchling
.pkg: _optional_hooks> python /opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/pyproject_api/_backend.py True hatchling.build
.pkg: get_requires_for_build_sdist> python /opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/pyproject_api/_backend.py True hatchling.build
.pkg: freeze> python -m pip freeze --all
.pkg: hatchling==1.24.2,packaging==24.0,pathspec==0.[12](https://github.com/Qiskit-Extensions/circuit-knitting-toolbox/actions/runs/8791924164/job/24127118171?pr=556#step:6:13).1,pip==24.0,pluggy==1.5.0,setuptools==69.5.1,tomli==2.0.1,trove-classifiers==2024.4.10,wheel==0.43.0
.pkg: build_sdist> python /opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/pyproject_api/_backend.py True hatchling.build
docs: install_package_deps> python -I -m pip install 'Sphinx>=3.0.0' 'cplex>=22.1.0.0; python_version < "3.12" and platform_machine != "arm64"' 'docplex>=2.23.222; python_version < "3.12" and platform_machine != "arm64"' 'ipykernel>=4.5.1' ipywidgets 'jupyter-sphinx>=0.3.2' matplotlib 'nbsphinx>=0.8.8' 'numpy>=1.23.0' pylatexenc 'qiskit-aer>=0.14.0.1' 'qiskit-ibm-runtime>=0.23.0' 'qiskit-sphinx-theme<2,>=1.14.0' 'qiskit<2.0,>=1.0.0' 'reno>=3.4.0' 'rustworkx>=0.14.0' 'scipy>=1.5.2' 'sphinx-autodoc-typehints>=1.12.0' 'sphinx-copybutton>=0.5.0' sphinx-reredirects
docs: install_package> python -I -m pip install --force-reinstall --no-deps /home/runner/work/circuit-knitting-toolbox/circuit-knitting-toolbox/.tox/.tmp/package/1/circuit_knitting_toolbox-0.7.0.tar.gz
docs: freeze> python -m pip freeze --all
docs: alabaster==0.7.16,annotated-types==0.6.0,asttokens==2.4.1,attrs==23.2.0,Babel==2.14.0,beautifulsoup4==4.12.3,bleach==6.1.0,certifi==2024.2.2,cffi==1.16.0,charset-normalizer==3.3.2,circuit-knitting-toolbox @ file:///home/runner/work/circuit-knitting-toolbox/circuit-knitting-toolbox/.tox/.tmp/package/1/circuit_knitting_toolbox-0.7.0.tar.gz#sha256=16929386adec23615c90a3ba5a4999890e[13](https://github.com/Qiskit-Extensions/circuit-knitting-toolbox/actions/runs/8791924164/job/24127118171?pr=556#step:6:14)3560d74f6323aeba8986e7ab7704,comm==0.2.2,contourpy==1.2.1,cplex==22.1.1.2,cryptography==42.0.5,cycler==0.12.1,debugpy==1.8.1,decorator==5.1.1,defusedxml==0.7.1,dill==0.3.8,docplex==2.27.239,docutils==0.21.1,dulwich==0.22.0,exceptiongroup==1.2.1,executing==2.0.1,fastjsonschema==2.19.1,fonttools==4.51.0,furo==2024.1.29,ibm-cloud-sdk-core==3.20.0,ibm-platform-services==0.53.4,idna==3.7,imagesize==1.4.1,importlib_metadata==7.1.0,importlib_resources==6.4.0,ipykernel==6.29.4,ipython==8.18.1,ipywidgets==8.1.2,jedi==0.19.1,Jinja2==3.1.3,jsonschema==4.21.1,jsonschema-specifications==2023.12.1,jupyter-sphinx==0.5.3,jupyter_client==8.6.1,jupyter_core==5.7.2,jupyterlab_pygments==0.3.0,jupyterlab_widgets==3.0.10,kiwisolver==1.4.5,MarkupSafe==2.1.5,matplotlib==3.8.4,matplotlib-inline==0.1.7,mistune==3.0.2,mpmath==1.3.0,nbclient==0.10.0,nbconvert==7.16.3,nbformat==5.10.4,nbsphinx==0.9.3,nest-asyncio==1.6.0,numpy==1.26.4,packaging==24.0,pandocfilters==1.5.1,parso==0.8.4,pbr==6.0.0,pexpect==4.9.0,pillow==10.3.0,pip==24.0,platformdirs==4.2.0,prompt-toolkit==3.0.43,psutil==5.9.8,ptyprocess==0.7.0,pure-eval==0.2.2,pycparser==2.22,pydantic==2.7.0,pydantic_core==2.18.1,Pygments==2.17.2,PyJWT==2.8.0,pylatexenc==2.10,pyparsing==3.1.2,pyspnego==0.10.2,python-dateutil==2.9.0.post0,PyYAML==6.0.1,pyzmq==26.0.2,qiskit==1.0.2,qiskit-aer==0.[14](https://github.com/Qiskit-Extensions/circuit-knitting-toolbox/actions/runs/8791924164/job/24127118171?pr=556#step:6:15).0.1,qiskit-ibm-runtime==0.23.0,qiskit-sphinx-theme==1.16.1,referencing==0.34.0,reno==4.1.0,requests==2.31.0,requests-ntlm==1.2.0,rpds-py==0.18.0,rustworkx==0.14.2,scipy==1.13.0,setuptools==69.5.1,six==1.16.0,snowballstemmer==2.2.0,soupsieve==2.5,Sphinx==7.3.7,sphinx-autodoc-typehints==2.1.0,sphinx-basic-ng==1.0.0b2,sphinx-copybutton==0.5.2,sphinx-reredirects==0.1.3,sphinxcontrib-applehelp==1.0.8,sphinxcontrib-devhelp==1.0.6,sphinxcontrib-htmlhelp==2.0.5,sphinxcontrib-jquery==4.1,sphinxcontrib-jsmath==1.0.1,sphinxcontrib-qthelp==1.0.7,sphinxcontrib-serializinghtml==1.1.10,stack-data==0.6.3,stevedore==5.2.0,symengine==0.11.0,sympy==1.12,tinycss2==1.2.1,tomli==2.0.1,tornado==6.4,traitlets==5.14.3,typing_extensions==4.11.0,urllib3==2.2.1,wcwidth==0.2.13,webencodings==0.5.1,websocket-client==1.7.0,wheel==0.43.0,widgetsnbextension==4.0.10,zipp==3.18.1
docs: commands[0]> python -c 'import shutil, pathlib; shutil.rmtree(pathlib.Path("docs") / "stubs", ignore_errors=True)'
docs: commands[1]> python -c 'import shutil, pathlib; shutil.rmtree(pathlib.Path("docs") / "_build" / "html" / ".doctrees", ignore_errors=True)'
docs: commands[2]> sphinx-build -j auto -W -T --keep-going docs/ docs/_build/html
Running Sphinx v7.3.7
making output directory... done
[autosummary] generating autosummary for: apidocs/circuit_cutting.rst, apidocs/index.rst, apidocs/utils.rst, circuit_cutting/cutqc/index.rst, circuit_cutting/cutqc/tutorials/tutorial_1_automatic_cut_finding.ipynb, circuit_cutting/cutqc/tutorials/tutorial_2_manual_cutting.ipynb, circuit_cutting/explanation/index.rst, circuit_cutting/how-tos/how_to_generate_exact_quasi_dists_from_sampler.ipynb, circuit_cutting/how-tos/how_to_generate_exact_sampling_coefficients.ipynb, circuit_cutting/how-tos/how_to_specify_cut_wires.ipynb, circuit_cutting/how-tos/index.rst, circuit_cutting/tutorials/01_gate_cutting_to_reduce_circuit_width.ipynb, circuit_cutting/tutorials/02_gate_cutting_to_reduce_circuit_depth.ipynb, circuit_cutting/tutorials/03_wire_cutting_via_move_instruction.ipynb, circuit_cutting/tutorials/04_automatic_cut_finding.ipynb, circuit_cutting/tutorials/index.rst, index.rst, install.rst, release-notes.rst
[autosummary] generating autosummary for: /home/runner/work/circuit-knitting-toolbox/circuit-knitting-toolbox/docs/stubs/circuit_knitting.cutting.DeviceConstraints.rst, /home/runner/work/circuit-knitting-toolbox/circuit-knitting-toolbox/docs/stubs/circuit_knitting.cutting.OptimizationParameters.rst, /home/runner/work/circuit-knitting-toolbox/circuit-knitting-toolbox/docs/stubs/circuit_knitting.cutting.PartitionedCuttingProblem.rst, /home/runner/work/circuit-knitting-toolbox/circuit-knitting-toolbox/docs/stubs/circuit_knitting.cutting.cut_gates.rst, /home/runner/work/circuit-knitting-toolbox/circuit-knitting-toolbox/docs/stubs/circuit_knitting.cutting.cut_wires.rst, /home/runner/work/circuit-knitting-toolbox/circuit-knitting-toolbox/docs/stubs/circuit_knitting.cutting.cutqc.build.rst, /home/runner/work/circuit-knitting-toolbox/circuit-knitting-toolbox/docs/stubs/circuit_knitting.cutting.cutqc.cut_circuit_wires.rst, /home/runner/work/circuit-knitting-toolbox/circuit-knitting-toolbox/docs/stubs/circuit_knitting.cutting.cutqc.evaluate_subcircuits.rst, /home/runner/work/circuit-knitting-toolbox/circuit-knitting-toolbox/docs/stubs/circuit_knitting.cutting.cutqc.generate_summation_terms.rst, /home/runner/work/circuit-knitting-toolbox/circuit-knitting-toolbox/docs/stubs/circuit_knitting.cutting.cutqc.reconstruct_full_distribution.rst, ..., /home/runner/work/circuit-knitting-toolbox/circuit-knitting-toolbox/docs/stubs/circuit_knitting.utils.metrics.cross_entropy.rst, /home/runner/work/circuit-knitting-toolbox/circuit-knitting-toolbox/docs/stubs/circuit_knitting.utils.observable_grouping.CommutingObservableGroup.rst, /home/runner/work/circuit-knitting-toolbox/circuit-knitting-toolbox/docs/stubs/circuit_knitting.utils.observable_grouping.ObservableCollection.rst, /home/runner/work/circuit-knitting-toolbox/circuit-knitting-toolbox/docs/stubs/circuit_knitting.utils.observable_grouping.observables_restricted_to_subsystem.rst, /home/runner/work/circuit-knitting-toolbox/circuit-knitting-toolbox/docs/stubs/circuit_knitting.utils.simulation.ExactSampler.rst, /home/runner/work/circuit-knitting-toolbox/circuit-knitting-toolbox/docs/stubs/circuit_knitting.utils.simulation.simulate_statevector_outcomes.rst, /home/runner/work/circuit-knitting-toolbox/circuit-knitting-toolbox/docs/stubs/circuit_knitting.utils.transforms.SeparatedCircuits.rst, /home/runner/work/circuit-knitting-toolbox/circuit-knitting-toolbox/docs/stubs/circuit_knitting.utils.transforms.separate_circuit.rst, /home/runner/work/circuit-knitting-toolbox/circuit-knitting-toolbox/docs/stubs/circuit_knitting.utils.transpiler_passes.ConsolidateResets.rst, /home/runner/work/circuit-knitting-toolbox/circuit-knitting-toolbox/docs/stubs/circuit_knitting.utils.transpiler_passes.RemoveFinalReset.rst
loading intersphinx inventory from https://docs.python.org/3/objects.inv...
loading intersphinx inventory from https://numpy.org/doc/stable/objects.inv...
loading intersphinx inventory from https://docs.scipy.org/doc/scipy/objects.inv...
loading intersphinx inventory from https://docs.quantum.ibm.com/api/qiskit/objects.inv...
loading intersphinx inventory from https://docs.quantum.ibm.com/api/qiskit-ibm-runtime/objects.inv...
loading intersphinx inventory from https://qiskit.github.io/qiskit-aer/objects.inv...
loading intersphinx inventory from https://www.rustworkx.org/objects.inv...
building [mo]: targets for 0 po files that are out of date
writing output... 
building [html]: targets for 19 source files that are out of date
updating environment: [new config] 68 added, 0 changed, 0 removed
reading sources... [ 17%] apidocs/circuit_cutting .. circuit_cutting/tutorials/02_gate_cutting_to_reduce_circuit_depth
reading sources... [ 33%] circuit_cutting/tutorials/03_wire_cutting_via_move_instruction .. stubs/circuit_knitting.cutting.cutqc.cut_circuit_wires
reading sources... [ 50%] stubs/circuit_knitting.cutting.cutqc.evaluate_subcircuits .. stubs/circuit_knitting.cutting.qpd.BaseQPDGate
reading sources... [ 67%] stubs/circuit_knitting.cutting.qpd.QPDBasis .. stubs/circuit_knitting.utils.conversion.quasi_to_real
scanning ./releasenotes/notes for current branch release notes

(Error in parallel process)
Traceback (most recent call last):
  File "/home/runner/work/circuit-knitting-toolbox/circuit-knitting-toolbox/.tox/docs/lib/python3.9/site-packages/sphinx/util/parallel.py", line 76, in _process
    ret = func(arg)
  File "/home/runner/work/circuit-knitting-toolbox/circuit-knitting-toolbox/.tox/docs/lib/python3.9/site-packages/sphinx/builders/__init__.py", line 458, in read_process
    self.read_doc(docname, _cache=False)
  File "/home/runner/work/circuit-knitting-toolbox/circuit-knitting-toolbox/.tox/docs/lib/python3.9/site-packages/sphinx/builders/__init__.py", line 497, in read_doc
    publisher.publish()
  File "/home/runner/work/circuit-knitting-toolbox/circuit-knitting-toolbox/.tox/docs/lib/python3.9/site-packages/docutils/core.py", line 234, in publish
    self.document = self.reader.read(self.source, self.parser,
  File "/home/runner/work/circuit-knitting-toolbox/circuit-knitting-toolbox/.tox/docs/lib/python3.9/site-packages/sphinx/io.py", line 107, in read
    self.parse()
  File "/home/runner/work/circuit-knitting-toolbox/circuit-knitting-toolbox/.tox/docs/lib/python3.9/site-packages/docutils/readers/__init__.py", line 76, in parse
    self.parser.parse(self.input, document)
  File "/home/runner/work/circuit-knitting-toolbox/circuit-knitting-toolbox/.tox/docs/lib/python3.9/site-packages/sphinx/parsers.py", line 83, in parse
    self.statemachine.run(inputlines, document, inliner=self.inliner)
  File "/home/runner/work/circuit-knitting-toolbox/circuit-knitting-toolbox/.tox/docs/lib/python3.9/site-packages/docutils/parsers/rst/states.py", line 169, in run
    results = StateMachineWS.run(self, input_lines, input_offset,
  File "/home/runner/work/circuit-knitting-toolbox/circuit-knitting-toolbox/.tox/docs/lib/python3.9/site-packages/docutils/statemachine.py", line 233, in run
    context, next_state, result = self.check_line(
  File "/home/runner/work/circuit-knitting-toolbox/circuit-knitting-toolbox/.tox/docs/lib/python3.9/site-packages/docutils/statemachine.py", line 445, in check_line
    return method(match, context, next_state)
  File "/home/runner/work/circuit-knitting-toolbox/circuit-knitting-toolbox/.tox/docs/lib/python3.9/site-packages/docutils/parsers/rst/states.py", line 2357, in explicit_markup
    nodelist, blank_finish = self.explicit_construct(match)
  File "/home/runner/work/circuit-knitting-toolbox/circuit-knitting-toolbox/.tox/docs/lib/python3.9/site-packages/docutils/parsers/rst/states.py", line 2369, in explicit_construct
    return method(self, expmatch)
  File "/home/runner/work/circuit-knitting-toolbox/circuit-knitting-toolbox/.tox/docs/lib/python3.9/site-packages/docutils/parsers/rst/states.py", line 2106, in directive
    return self.run_directive(
  File "/home/runner/work/circuit-knitting-toolbox/circuit-knitting-toolbox/.tox/docs/lib/python3.9/site-packages/docutils/parsers/rst/states.py", line 2[15](https://github.com/Qiskit-Extensions/circuit-knitting-toolbox/actions/runs/8791924164/job/24127118171?pr=556#step:6:16)6, in run_directive
    result = directive_instance.run()
  File "/home/runner/work/circuit-knitting-toolbox/circuit-knitting-toolbox/.tox/docs/lib/python3.9/site-packages/reno/sphinxext.py", line 114, in run
    with loader.Loader(conf) as ldr:
  File "/home/runner/work/circuit-knitting-toolbox/circuit-knitting-toolbox/.tox/docs/lib/python3.9/site-packages/reno/loader.py", line 62, in __init__
    self._load_data()
  File "/home/runner/work/circuit-knitting-toolbox/circuit-knitting-toolbox/.tox/docs/lib/python3.9/site-packages/reno/loader.py", line 89, in _load_data
    self._scanner = scanner.Scanner(self._config)
  File "/home/runner/work/circuit-knitting-toolbox/circuit-knitting-toolbox/.tox/docs/lib/python3.9/site-packages/reno/scanner.py", line 511, in __init__
    self._repo = RenoRepo(self.reporoot)
  File "/home/runner/work/circuit-knitting-toolbox/circuit-knitting-toolbox/.tox/docs/lib/python3.9/site-packages/dulwich/repo.py", line 1195, in __init__
    raise UnsupportedExtension(extension)
dulwich.repo.UnsupportedExtension: b'worktreeConfig'

Sphinx parallel build error:
dulwich.repo.UnsupportedExtension: b'worktreeConfig'
docs: exit 2 (31.75 seconds) /home/runner/work/circuit-knitting-toolbox/circuit-knitting-toolbox> sphinx-build -j auto -W -T --keep-going docs/ docs/_build/html pid=2907
.pkg: _exit> python /opt/hostedtoolcache/Python/3.9.[19](https://github.com/Qiskit-Extensions/circuit-knitting-toolbox/actions/runs/8791924164/job/24127118171?pr=556#step:6:20)/x64/lib/python3.9/site-packages/pyproject_api/_backend.py True hatchling.build
  docs: FAIL code 2 (88.24=setup[56.43]+cmd[0.03,0.03,31.75] seconds)
  evaluation failed :( (88.35 seconds)

**Comment by caleb-johnson** [comment]
I reverted the change from #538 in a PR failing for this same reason, and it did not fix the problem.

**Comment by caleb-johnson** [comment]
https://github.com/Qiskit-Extensions/qiskit-experiments

Qiskit Experiments CI failing w same error

**Comment by caleb-johnson** [comment]
https://github.com/jelmer/dulwich/issues/1285

This sees to be our problem

**Comment by caleb-johnson** [comment]
> Qiskit Experiments CI failing w same error

https://github.com/Qiskit-Extensions/qiskit-experiments/pull/1448
